/* Generated by wayland-scanner 1.24.0 */

#ifndef LVR_PRIVATE_HANDLE_CLIENT_PROTOCOL_H
#define LVR_PRIVATE_HANDLE_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_lvr_private_handle The lvr_private_handle protocol
 * private handle
 *
 * @section page_desc_lvr_private_handle Description
 *
 * This protocol allows a compositor to associate a Wayland client with external
 * IPC mechanisms, such as D-Bus.
 *
 * Immediately after a client binds to the lvr_private_handle_manager global, the
 * compositor sends the client a compositor-generated, opaque identifier exactly
 * once. The identifier is a string of up to 64 characters and consists only of
 * alphanumeric characters and underscores. It is generated with sufficient
 * randomness to prevent other clients from guessing it.
 *
 * The client may use this handle to identify itself to external IPC mechanisms
 * through means not defined by this protocol.
 *
 * @section page_ifaces_lvr_private_handle Interfaces
 * - @subpage page_iface_lvr_private_handle_manager - private handle manager
 * @section page_copyright_lvr_private_handle Copyright
 * <pre>
 *
 * Copyright © 2026 Eduardo Hopperdietzel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct lvr_private_handle_manager;

#ifndef LVR_PRIVATE_HANDLE_MANAGER_INTERFACE
#define LVR_PRIVATE_HANDLE_MANAGER_INTERFACE
/**
 * @page page_iface_lvr_private_handle_manager lvr_private_handle_manager
 * @section page_iface_lvr_private_handle_manager_desc Description
 *
 * This interface allows a compositor to announce support for private handles.
 * @section page_iface_lvr_private_handle_manager_api API
 * See @ref iface_lvr_private_handle_manager.
 */
/**
 * @defgroup iface_lvr_private_handle_manager The lvr_private_handle_manager interface
 *
 * This interface allows a compositor to announce support for private handles.
 */
extern const struct wl_interface lvr_private_handle_manager_interface;
#endif

/**
 * @ingroup iface_lvr_private_handle_manager
 * @struct lvr_private_handle_manager_listener
 */
struct lvr_private_handle_manager_listener {
	/**
	 * private handle
	 *
	 * 
	 */
	void (*handle)(void *data,
		       struct lvr_private_handle_manager *lvr_private_handle_manager,
		       const char *handle);
};

/**
 * @ingroup iface_lvr_private_handle_manager
 */
static inline int
lvr_private_handle_manager_add_listener(struct lvr_private_handle_manager *lvr_private_handle_manager,
					const struct lvr_private_handle_manager_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) lvr_private_handle_manager,
				     (void (**)(void)) listener, data);
}

#define LVR_PRIVATE_HANDLE_MANAGER_DESTROY 0

/**
 * @ingroup iface_lvr_private_handle_manager
 */
#define LVR_PRIVATE_HANDLE_MANAGER_HANDLE_SINCE_VERSION 1

/**
 * @ingroup iface_lvr_private_handle_manager
 */
#define LVR_PRIVATE_HANDLE_MANAGER_DESTROY_SINCE_VERSION 1

/** @ingroup iface_lvr_private_handle_manager */
static inline void
lvr_private_handle_manager_set_user_data(struct lvr_private_handle_manager *lvr_private_handle_manager, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) lvr_private_handle_manager, user_data);
}

/** @ingroup iface_lvr_private_handle_manager */
static inline void *
lvr_private_handle_manager_get_user_data(struct lvr_private_handle_manager *lvr_private_handle_manager)
{
	return wl_proxy_get_user_data((struct wl_proxy *) lvr_private_handle_manager);
}

static inline uint32_t
lvr_private_handle_manager_get_version(struct lvr_private_handle_manager *lvr_private_handle_manager)
{
	return wl_proxy_get_version((struct wl_proxy *) lvr_private_handle_manager);
}

/**
 * @ingroup iface_lvr_private_handle_manager
 */
static inline void
lvr_private_handle_manager_destroy(struct lvr_private_handle_manager *lvr_private_handle_manager)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_private_handle_manager,
			 LVR_PRIVATE_HANDLE_MANAGER_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_private_handle_manager), WL_MARSHAL_FLAG_DESTROY);
}

#ifdef  __cplusplus
}
#endif

#endif
